# Generated by Django 5.1.1 on 2024-12-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teabookings', '0002_tealesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tealesson',
            name='history',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tealesson',
            name='itemsNeeded',
            field=models.CharField(max_length=1000),
        ),
    ]
