# Generated by Django 5.1.1 on 2024-12-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teabookings', '0006_cartitem_selected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
