# Generated by Django 5.1.1 on 2024-12-13 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teabookings', '0008_booking_bookingitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tealesson',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favoritelist', to=settings.AUTH_USER_MODEL),
        ),
    ]
