# Generated by Django 5.1.1 on 2024-12-13 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teabookings', '0009_alter_tealesson_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filterName', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='tealesson',
            name='filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter', to='teabookings.filter'),
        ),
    ]
